#!/bin/bash
# FaceSeek Production Deployment & Test Guide
# This guide covers creating the Acun Ilıcalı test user and running search tests

echo "=========================================="
echo "STEP 1: Deploy Latest Changes to VPS"
echo "=========================================="
echo ""
echo "Run these commands on the VPS (as root):"
echo ""
echo "  cd /opt/faceseek"
echo "  git pull origin main"
echo "  cd backend"
echo ""

echo "=========================================="
echo "STEP 2: Create Test User (On VPS)"
echo "=========================================="
echo ""
echo "Make sure Backend API is running, then run:"
echo ""
echo "  cd /opt/faceseek/backend"
echo "  python3 scripts/create_acun_test_user.py"
echo ""
echo "Expected output:"
echo "  - User created or found in database"
echo "  - JWT token generated"
echo "  - Credentials saved to .test_credentials.json"
echo ""

echo "=========================================="
echo "STEP 3: Test Search Endpoint"
echo "=========================================="
echo ""
echo "Test credentials will be in:"
echo "  /opt/faceseek/backend/.test_credentials.json"
echo ""
echo "Example search test (replace TOKEN with actual JWT):"
echo ""
echo "  curl -X POST https://face-seek.com/api/search-face \\"
echo "    -H 'Authorization: Bearer <JWT_TOKEN>' \\"
echo "    -F 'file=@acun_photo.jpg'"
echo ""
echo "Expected response:"
echo "  {"
echo "    \"status\": \"success\","
echo "    \"results\": ["
echo "      {"
echo "        \"similarity\": 0.92,"
echo "        \"person_name\": \"...\","
echo "        \"source_url\": \"...\""
echo "      }"
echo "    ]"
echo "  }"
echo ""

echo "=========================================="
echo "IMPORTANT NOTES"
echo "=========================================="
echo ""
echo "1. Test Credentials:"
echo "   Email: acun@faceseek.test"
echo "   Password: TestAcun@2024!"
echo "   Username: acun_ilicali"
echo "   Tier: unlimited"
echo "   Credits: 1000"
echo ""
echo "2. Vector Database Status:"
echo "   - Milvus collection: EyeOfWebFaceDataMilvus"
echo "   - Indexed faces: ~13,767"
echo "   - Embedding model: buffalo_l (512-dim)"
echo "   - Similarity threshold: 0.6"
echo ""
echo "3. When testing:"
echo "   - Use high-quality Acun Ilıcalı images"
echo "   - Test with 3 different images to verify consistency"
echo "   - Check similarity scores (should be > 0.6 for matches)"
echo ""
echo "4. Troubleshooting:"
echo "   - If 401 Unauthorized: Check JWT token validity"
echo "   - If 0 results: Check Milvus collection and threshold"
echo "   - Check logs: journalctl -u faceseek-backend -f"
echo ""
