services:
  faceseek_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: faceseek_frontend
    ports:
      - "3002:3000"
    networks:
      - face_seek_network

  faceseek_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: faceseek_backend
    ports:
      - "8003:8000"
    networks:
      - face_seek_network

networks:
  face_seek_network:
    driver: bridge
